SET C51INC=D:\Keil_v5\C51\Inc;D:\Keil_v5\C51\Inc\Cygnal
SET C51LIB=D:\Keil_v5\C51\Lib
SET CPU_TYPE=C8051F120
SET CPU_VENDOR=Silicon Labs
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x05F5E100
"D:\Keil_v5\C51\BIN\A51.EXE" @STARTUP._ia
"D:\Keil_v5\C51\BIN\C51.EXE" @FlashTestMain.__i
"D:\Keil_v5\C51\BIN\C51.EXE" @F120_FlashPrimitives.__i
"D:\Keil_v5\C51\BIN\C51.EXE" @MyDebug.__i
"D:\Keil_v5\C51\BIN\BL51.EXE" @FlashTest.lnp
